swagger: "2.0"
info:
    description: 中午吃什麼
    version: 0.0.0
    title: "[2018][WebGene] - TsiahPng"

# Added by API Auto Mocking Plugin
host: tsiahpng.appspot.com
basePath: /
#securityDefinitions:
#  Bearer:
#    type: apiKey
#    name: Authorization
#    in: header

schemes:
    - https

tags:
    - name: Site
      description: 活動站
    - name: Admin
      description: 後台

paths:
    
    /auth/login:
            post:
                tags:
                    - Admin
                summary: 登入
                parameters:
                  - in: body
                    name: User Info
                    description: The user to create.
                    schema:
                      type: object
                      required:
                        - userName
                      properties:
                        username:
                          type: string
                          example: "admin"
                        password:
                          type: string
                          example: "0000"
                responses:
                    200:
                        description: OK
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                            img:
                                                type: string

    /api/getRestaurantsList:
        get:
            tags:
                - Site
            summary: 取得餐廳列表
            responses:
                200:
                    description: OK
                    schema:
                        type: object
                        properties:
                            Restaurants:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        img:
                                            type: string
                                        name:
                                            type: string
                                        price:
                                            type: string
                                        purpose:
                                            type: string
    /tsiahpng/RestaurantAdd:
            post:
                tags:
                    - Admin
                summary: 新增餐廳
                parameters:
                  - in: body
                    name: User Info
                    description: The user to create.
                    schema:
                      type: object
                      required:
                        - userName
                      properties:
                        name:
                          type: string
                          example: "餐廳"
                        price:
                          type: string
                          example: "便宜"
                        purpose:
                          type: string
                          example: "一般"
                responses:
                    200:
                        description: OK
                        schema:
                            type: object
                            
                            properties:
                                result:
                                    type: string                                    


    /tsiahpng/RestaurantsList:
            get:
                tags:
                    - Admin
                summary: 取得餐廳列表
                responses:
                    200:
                        description: OK
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            img:
                                                type: string
                                            name:
                                                type: string
                                            price:
                                                type: string
                                            purpose:
                                                type: string
    